language: go
sudo: false
go:
- 1.6.3
- tip

matrix:
  allow_failures:
  - go: tip

env:
  - GIMME_OS=darwin GIMME_ARCH=amd64

script:
- go test -v ./...
- go build

deploy:
  provider: releases
  api_key:
    secure: hWSHSdCq1qGR2yd5QA8TxZ2R+7XlZGMxQH3DfFFAkgL4QuQzKF/2yrP57N/I6LINfwTQLMdsmYtsTf0s1NsNrnQ1R/zgpywBrAkynWk8PSv8oLpGqdEfr8xXDsjwzWIdXoaQbyvGP7skvfzDnYXWVOF5RGUQcSPvXLQOz3OVvUkZ7Vzimw3mIN47IRrIQlCHr6VUa5bvkKmQsx2VffOLVU01PkoU6MsDy1RLgA7o0uJSAAuaPGxEiIetMN/Yh53+AtKvhFwaY/T192wVau9M1uLnYA/g80My0emxGWAZJIlSwiDI6h/r9hYM8hTc+QOKKC8SwhUUbC5uzSTlzoO0t8qIFTNRzPOKpD6wd3Se7t6amCeR5DloofIrHqMx9X31x3U8jORITbO7Zz6y/wLEv5H0hKoCAPV34jxQvi/Jo2GqBOBHUHdY9DXU9e2pLOzodonSk3fIXWsgF5MwaNiq//NsbyuMsglSIEL03l7bpl5y/Z6HBFhlxRYlzlGaQYZWagE7lrkTUKKYS6l9zKet69qJrNCWAQYt9JD2pvQbpqo/jcJx5dugwiYhICQmEplyS9Gaw4CrXxKIUF9+BEwOGIOFCN5M/qONmRsSMMj0OSAiUNwr3jJx2HwoqdNVYA87s6/J9gF2pOTXM4i5BJNYTjJXwHCRkW8j4+WlTlkr6g8=
  file: osx-sync-env
  skip_cleanup: true
  overwrite: true
  on:
    repo: pastjean/osx-sync-env
    tags: true
