on: [push, pull_request]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
    - run: |
        go test -v ./...
        go vet ./...
        golint ./...
    - run: GOOS=darwin GOARCH=amd64 go build
